services:
  - type: web
    name: hospital-management-system
    runtime: image
    repo: https://github.com/charllote122/hospital-management
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hospital_api.settings
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_HOURS
        value: 24
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: hospital-management-system.onrender.com
      - key: DISABLE_COLLECTSTATIC
        value: 1
