services:
  - type: web
    name: hospital-management-system
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn hospital_api.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hospital_api.settings
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_HOURS
        value: 24
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: hospital-management-system.onrender.com
      - key: DB_ENGINE
        value: django.db.backends.postgresql
    plan: free
