# Generated by Django 4.1.13 on 2026-08-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('antidepressant', 'Antidepressant'), ('antihistamine', 'Antihistamine'), ('antiviral', 'Antiviral'), ('painkiller', 'Painkiller'), ('vitamin', 'Vitamin'), ('supplement', 'Supplement'), ('other', 'Other')], default='other', max_length=50)),
                ('manufacturer', models.CharField(max_length=200)),
                ('dosage_form', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('instructions', models.TextField()),
                ('refills', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('prescribed_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prescriptions', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_prescriptions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Pharmacy Prescription',
                'verbose_name_plural': 'Pharmacy Prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
    ]
