# Generated by Django 4.1.13 on 2026-08-14 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('patient', 'Patient Statistics'), ('appointment', 'Appointment Statistics'), ('revenue', 'Revenue Statistics'), ('inventory', 'Inventory Statistics'), ('pharmacy', 'Pharmacy Statistics'), ('lab', 'Lab Statistics'), ('staff', 'Staff Statistics'), ('satisfaction', 'Patient Satisfaction'), ('wait_time', 'Wait Time'), ('turnover', 'Turnover Rate'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(default='Analytics Report', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('previous_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('change_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_period', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('chart_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['metric_type', 'date'], name='analytics_a_metric__560532_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['-created_at'], name='analytics_a_created_a855f1_idx'),
        ),
    ]
